### ISSUE TITLE
Please upload the AppImage to GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [c3er/mdview#1]
https://github.com/c3er/mdview/blob/eff1c058c60c9b7592ea9d8ffd1a93f5b998e93d/package.json#L35

Please upload the AppImage to GitHub Releases, thanks.

**Comment by c3er** [comment]
Added an AppImage to [Release 1.1.2](https://github.com/c3er/mdview/releases/tag/v1.1.2). I did not test this package, because I built it under the Linux Subsystem for Windows. Feel free to reopen this issue, if the AppImage doe not work.

Sorry for the late response. I got no notification for this issue. I hope the notification setting "Automatically watch repositories" will fix this in the future.
