### ISSUE TITLE
The Github link is broken

### ISSUE THREAD

**Issue by Stokestack** [c3er/mdview#17]
The alleged link to binaries in the descriptive text is no good.

**Comment by Stokestack** [comment]
Also:

> For Windows, there is an installer package and a ZIP archive. For Linux, there is an AppImage package.

And for Mac?

**Comment by c3er** [comment]
Thanks for notifying me about this embarrassment!

I already [fixed](https://github.com/c3er/mdview/commit/5643da7fbdad935ede9afc069aa464ff4446c130) the link. Is it okay, if I don't publish a new release immediately? I feel, since the last release came to little too justify a new one.

>> For Windows, there is an installer package and a ZIP archive. For Linux, there is an AppImage package.
>
> And for Mac?

To build a Mac package, I'd need an actual Mac computer, which I don't posses. Also note, that the Linux package is not tested, since I build it on Windows with WSL. So if you (or someone) find any issue with the Application on Linux, I'd be happy to get notified about this

**Comment by Stokestack** [comment]
Ha, "embarrassment!" No worries! And you're welcome.

I'll let you know if I find anything. Unfortunately I don't have time right now to install everything necessary for a Mac build, but there is a need for this tool. I'm not the only one who's baffled by the lack of such a viewer.
