### ISSUE TITLE
Mermaid diagramming/visualization support?

### ISSUE THREAD

**Issue by djs-zmtc** [c3er/mdview#21]
**REQUEST:** Are there any plans to implement rendering of Mermaid diagramming and visualization extensions to Markdown? 

Just curious as this would be nice to have, but I understand if something like this would complicate an already very useful tool. Thanks for all your work on this viewer -- I use it pretty much every day.

**Comment by c3er** [comment]
Thanks for filing the issue!

I tried adding Mermaid support during implementation of issue #13 but gave up on this. See [this comment](https://github.com/c3er/mdview/issues/13#issuecomment-876005292). I keep this issue here open and will take a deeper look into this.

But it may take a while. I have currently not much time and energy to work on this hobby project and issue #20 has higher priority.

> Thanks for all your work on this viewer -- I use it pretty much every day.

Thank you☺

**Comment by c3er** [comment]
I just took a little deeper look and implementing this feature may take a while -- if I'll do it at all.

Mermaid cannot be used with the old `require` method (see [this issue](https://github.com/mermaid-js/mermaid/issues/2677) and [this](https://github.com/mermaid-js/mermaid/issues/2559)). Therefore the code has to be changed to use `import` statements instead of the `require` function.

A small experiment in the past to use `import` was not successful. But I'll try it again and a little harder.

I'll post an update when there are further news.

**Comment by c3er** [comment]
Good news: I found a workaround to integrate Mermaid. [Version 2.8.0](https://github.com/c3er/mdview/releases/tag/v2.8.0) can now display Mermaid diagrams.
