### ISSUE TITLE
[Enhancement] Be available in scoop installer

### ISSUE THREAD

**Issue by RaffaeleBianc0** [c3er/mdview#36]
It would be nice if mdview was available in one of the scoop buckets. :-)

**Comment by c3er** [comment]
Thanks for filing this issue!

I'll see that the next version will be available with a Scoop manifest. Also I'll try to add the application to the [extras bucket](https://github.com/ScoopInstaller/Extras).

I just filed [an issue to the electron-builder project](https://github.com/electron-userland/electron-builder/issues/7662). Though, I don't have much hope yet that electron-builder will integrate this or even in a short enough time to save me from implementing additional scripts for that.

**Comment by c3er** [comment]
The application can now be installed via this command:

```
scoop install https://github.com/c3er/mdview/releases/latest/download/mdview.json
```

Unfortunately, Markdown Viewer cannot be added to the Extras bucket yet, because it does not fulfill the criteria "Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)".

I'm closing this issue. Don't hesitate to open another issue, if you're something missing or something doesn't work as expected.
