### ISSUE TITLE
when to set EULA= ? does MIT license need user approval?

### ISSUE THREAD

**Issue by mralusw** [c3er/mdview#46]
For example I see that https://github.com/wimpysworld/deb-get/blob/main/01-main/packages/mdview has an EULA (thus prompting for confirmation). But it's MIT-licensed, just like `deb-get` itself. I somehow doubt that among all the other packages (none of which has a non-empty `EULA=`, except for chrome), there are no other MIT's.

**Comment by c3er** [comment]
Thanks for filing this issue, though I'm afraid this is not the right repository for this question. The `WEBSITE` entry in this package file links to *another tool* named "mdview"🙂 See https://github.com/mapitman/mdview

I think, it is the best to ask the question either in the right "mdview" repository or in this "deb-get" repository.

To answer your question with my opinion/thesis without any relation to any particular project and/or mechanism: I think, any license needs a confirmation of the user. Virtually anything that is not public domain has *some* kind of restriction. See this paragraph in the MIT license:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

So, anyone who distributes [my software](https://github.com/c3er/mdview) has to add my copyright notice at some place:

> Copyright 2018 Christian Dreier, https://github.com/c3er/mdview

I'm closing this issue, since I have nothing to do with neither mapitman's mdview nor this package repository, which I actually even didn't know about up to now.

**Comment by mralusw** [comment]
Sorry about that, this was meant to go into [deb-get](https://github.com/wimpysworld/deb-get), but I was simultaneously checking out the actual repo (i.e. this one) and... things got mixed up

**Comment by c3er** [comment]
No problem. But as stated: This is *not* the actual repo -- just one with the same name😂

**Comment by mralusw** [comment]
Right, that was *another*, *separate* mistake on my part :(
