### ISSUE TITLE
Feature request: Standalone portable viewer, auto-open file with same name

### ISSUE THREAD

**Issue by ggppjj** [c3er/mdview#56]
Hello!

I like the idea of including documentation as markdown with some of my projects, and it would seem that the best way to do that would be to include a portable markdown viewer to render them. 

I haven't found a good solution yet, and was wondering what your thoughts were as to bundling this as a no-install portable app were. In my own head (and I'm 100% willing to admit that this might be weird/bad), the most ideal setup would be for the exe to have the name of the document it's intended to view, and for it to auto-open that document in the same directory if found.

That way, I can distribute:
* Program.exe
* readme.md
* readme.exe

And maintain a single readme.md that also acts as the readme for Github.

Yours was the closest I could find to a project that suits my personal wants here, so I figured it would be worth reaching out to see what your thoughts were as to the viability.

**Comment by thmmsn** [comment]
Good idea with a portable application! However, using a README.exe, auto open, etc,… can be associated with malware, and users might hesitate to open it. What about using a readme.html file, bundled with some css and linking the markdown-file from the html? Those who can read plain markdown can still do that, and those who prefer formatted text can open it in the browser.

**Comment by ggppjj** [comment]
My own use-case would primarily be to distribute documentation internally as easily as possible, so the thought to auto-open an md file would only really be tailored for this process so that less technically-minded people at my office don't have to figure out what they're doing.

Perhaps a popup to allow the user to confirm the auto-open before it attempts to read the file? My thoughts along these lines would be to only trigger the automatic opening if both:

1. The portable mdview executable has been renamed.
1. There is a matching .md file in the same directory.

Adding a popup that then asks "Display filename?" would, I think, alleviate concerns with that association.

**Comment by c3er** [comment]
Hi, thank you for filing this issue!

This idea is really a little weird, but I could implement this. But I have another idea, which doesn't need any changes to the tool and might even be better: just add a properly named batch file next to the portable distribution (i.e. the extracted ZIP file) with this content:

```cmd
start /B mdview\mdview %~dpn0.md
```

![Screenshot of file explorer showing suggestion](https://github.com/user-attachments/assets/5f4cda88-a836-4369-93d4-c2cef45c8828)

This way, you can have an arbitrary count of Markdown files without adding a ~170 MB overhead for each.

What do you think about this?

Explanations for the command line:

- `start /B` starts something "in the background", i.e. the console window does only flicker after double-clicking the batch file instead of staying open.
- I decided to put the distribution in its own subfolder, so non-technical people don't get scared-off as fast by seeing DLL files, therefore `mdview\mdview`.
    - The part before the backslash is that subfolder
    - The part after the backslash is the EXE file. The extension `.exe` can be omitted.
- `%~dpn0` is a pointer to the batch file:
    - `d` is the drive
    - `p` is the folder path
    - `n` is the batch file without extension. `f` would include the extension

**Comment by ggppjj** [comment]
Not a bad option, could remove the need for a batch file also with a windows shortcut and added parameter also. I'll consider this approach for now, with, say, a hidden folder for the docs and a hidden folder for the viewer, with a toplevel folder of shortcuts to each doc. Thanks!

I hadn't considered the download size considering Electron with the original thought, though, that is a good point. I can host it internally as described above.

I'll have to think about this a bit further, and the specific weird thing I'm looking to do may end up being better as its own project considering I have goals that aren't particularly typically useful for a more general markdown viewer to aim for. It also might end up just being a bad idea that wasn't fully thought out at the asking, haha. 

Thanks for the reply!
